services:
  app:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:4200"
    depends_on:
      - db
      - api
  
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3333:3333"
    environment:
      PG_HOST: db
      PG_USER: postgres
      PG_PASSWORD: postgres
      PG_DATABASE: restaurantdb
      PG_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurantdb
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./insert_products.sql:/docker-entrypoint-initdb.d/insert_products.sql
      - pgdata:/var/lib/postgresql/data
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - db

volumes:
  pgdata: